# Generated by Django 4.2.5 on 2023-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image_url',
            field=models.CharField(default='https://cdn2.thecatapi.com/images/FTd8l4EXq.jpg', max_length=400),
        ),
    ]
